mysql:
    container_name: mysqlb
    image: rafaelviva/mysql:2020-06-17
    ports:
       - "3308:3308"
    environment:
      MYSQL_ROOT_PASSWORD: root
wordpress:
    container_name: php
    image: rafaelviva/php
    volumes:
      - ./codigo-fonte:/var/www/html
    ports:
      - 80:80
    links:
      - mysql:db
