mysql:
    container_name: mysqlb
    image: rafaelviva/mysql:2020-07-21
    ports:
<<<<<<< HEAD
       - "3308:3308"
=======
       - "3306:3306"
>>>>>>> 40ceb74b97aa297a8fd987c1edf70366823c75ff
    environment:
      MYSQL_ROOT_PASSWORD: root
wordpress:
    container_name: php
    image: rafaelviva/php
    volumes:
      - ./codigo-fonte:/var/www/html
    ports:
      - 80:80
    links:
      - mysql:db
